In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [23]:
df = pd.read_excel("mrtssales92-present.xlsx").set_index("Index").T
for col in df.columns:
    df[col] = df[col].replace("(NA)", np.nan)
    df[col] = df[col].replace("(S)", np.nan)
df

Index,"Retail and food services sales, total",Retail sales and food services excl motor vehicle and parts,Retail sales and food services excl gasoline stations,Retail sales and food services excl motor vehicle and parts and gasoline stations,"Retail sales, total","Retail sales, total (excl. motor vehicle and parts dealers)",GAFO(1),Motor vehicle and parts dealers,Automobile and other motor vehicle dealers,Automobile dealers,...,"Gift, novelty, and souvenir stores",Used merchandise stores,Nonstore retailers,Electronic shopping and mail-order houses,Fuel dealers,Food services and drinking places,Drinking places,Restaurants and other eating places,Full service restaurants,Limited service eating places
Jan. 1992,146376,116565,134277,104466,130683,100872,33906,29811,26788,25800,...,658,371,6860,2692,1916,15693,1049.0,13325,6887.0,6438
Feb. 1992,147079,115862,135499,104282,131244,100027,35220,31217,28203,27031,...,798,402,6059,2285,1627,15835,1026.0,13474,6937.0,6537
Mar. 1992,159336,124200,147064,111928,142488,107352,38731,35136,31684,30195,...,714,419,6297,2484,1537,16848,1074.0,14346,7245.0,7101
Apr. 1992,163669,127587,151226,115144,147175,111093,40548,36082,32547,30583,...,801,393,6022,2506,1341,16494,1031.0,14065,7000.0,7065
May 1992,170068,133608,156619,120159,152420,115960,42213,36460,32883,31095,...,900,435,5803,2483,1163,17648,1047.0,15077,7532.0,7545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Apr. 2021,625527,481396,578253,434122,558181,414050,119664,144131,134233,122215,...,1298,1780,85066,76206,2614,67346,NaN,61717,NaN,33008
May 2021,643099,500389,592919,450209,570641,427931,126686,142710,133232,121429,...,1423,1657,84422,76293,2209,72458,NaN,66471,NaN,34025
Jun. 2021,635437,498169,584134,446866,562929,425661,124474,137268,127542,115655,...,1616,1591,85052,77056,2146,72508,NaN,66346,NaN,33892
Jul. 2021,634486,500441,580997,446952,558031,423986,127008,134045,124297,113575,...,1730,1781,80605,72804,2026,76455,NaN,70011,NaN,35415
Aug. 2021(p),631060,502858,577811,449609,556698,428496,129536,128202,118335,108475,...,1597,1732,85624,77947,2039,74362,NaN,66913,NaN,34256

In [24]:
df.to_csv("mrtssales_92-present.csv")